// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-L2gvsLvUtqRt302X2Ylw4WvBoI5XH1A',
    appId: '1:900121287062:web:c0ca5c2bf08dd43d8b25b7',
    messagingSenderId: '900121287062',
    projectId: 'shufaa-98465',
    authDomain: 'shufaa-98465.firebaseapp.com',
    storageBucket: 'shufaa-98465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_dYtRaDAlBR4ws5hUpOXQjDOHFhCOX8g',
    appId: '1:900121287062:android:ef1a360937d877088b25b7',
    messagingSenderId: '900121287062',
    projectId: 'shufaa-98465',
    storageBucket: 'shufaa-98465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmh8z8PYR-GJMzLNrfvINgUSnS624l8OQ',
    appId: '1:900121287062:ios:1572ee1cd42b0caf8b25b7',
    messagingSenderId: '900121287062',
    projectId: 'shufaa-98465',
    storageBucket: 'shufaa-98465.appspot.com',
    iosBundleId: 'com.example.shufaaCat03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmh8z8PYR-GJMzLNrfvINgUSnS624l8OQ',
    appId: '1:900121287062:ios:1572ee1cd42b0caf8b25b7',
    messagingSenderId: '900121287062',
    projectId: 'shufaa-98465',
    storageBucket: 'shufaa-98465.appspot.com',
    iosBundleId: 'com.example.shufaaCat03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-L2gvsLvUtqRt302X2Ylw4WvBoI5XH1A',
    appId: '1:900121287062:web:0e79c1105db30c738b25b7',
    messagingSenderId: '900121287062',
    projectId: 'shufaa-98465',
    authDomain: 'shufaa-98465.firebaseapp.com',
    storageBucket: 'shufaa-98465.appspot.com',
  );
}
